### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by thewilloftheshadow** [thewilloftheshadow/reache#1]
- [x] Rename V-Neck
- [x] Enable invoice only
- [x] Reorder 
- [x] Name, Email, Phone Number
- [x] Retitle payment button

## Reorder

Crew Neck - Youth
Crew Neck - Adult
V-Neck Adult
Crew Neck Toddler
Onesie
.
LS Youth
LS Adult
Zippered Jacket - Youth
Zippered Jacket - Adult
Pullover Hoodie - Adult
